; ==============================================================================
; DebianXRDP-Pro
; XRDP Configuration
; ==============================================================================

[Globals]

; ------------------------------------------------------------------------------
; Basic Settings
; ------------------------------------------------------------------------------

fork=true
port=3389
use_vsock=false
tcp_nodelay=true
tcp_keepalive=true

; ------------------------------------------------------------------------------
; Security
; ------------------------------------------------------------------------------

security_layer=negotiate
crypt_level=high
allow_channels=true
max_bpp=32

; ------------------------------------------------------------------------------
; Login
; ------------------------------------------------------------------------------

autorun=Xorg

; ------------------------------------------------------------------------------
; Logging
; ------------------------------------------------------------------------------

enable_syslog=true
syslog_level=INFO

; ------------------------------------------------------------------------------
; Bitmap Cache
; ------------------------------------------------------------------------------

bitmap_cache=true
bitmap_compression=true
bulk_compression=true

; ------------------------------------------------------------------------------
; Channel Support
; ------------------------------------------------------------------------------

channel_code=true
rdpdr=true
rdpsnd=true
cliprdr=true
drdynvc=true

; ------------------------------------------------------------------------------
; Session Types
; ------------------------------------------------------------------------------

[Xorg]

name=Xorg

lib=libxup.so

username=ask

password=ask

ip=127.0.0.1

port=-1

code=20
